DROP TABLE IF EXISTS TB_USUARIO;
DROP TABLE IF EXISTS TB_USUARIO;
DROP TABLE IF EXISTS TB_USUARIO;
DROP TABLE IF EXISTS TB_USUARIO;
CREATE TABLE TB_USUARIO(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NOME TEXT(100),
SENHA TEXT(30)
);
